services:
  - type: web
    name: ip-sakti-sahayak
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
